// GENERATED by scripts/generate-translations.js — do not edit by hand.
// Regenerate with: npm run generate:translations

import { nlddButtonTranslations } from '../components/actions/button/button.i18n.js';
import { nlddIconButtonTranslations } from '../components/actions/icon-button/icon-button.i18n.js';
import { nlddMenuTranslations } from '../components/actions/menu/menu.i18n.js';
import { nlddSplitButtonTranslations } from '../components/actions/split-button/split-button.i18n.js';
import { nlddToolbarTranslations } from '../components/actions/toolbar/toolbar.i18n.js';
import { nlddAvatarGroupTranslations } from '../components/content/avatar-group/avatar-group.i18n.js';
import { nlddAvatarTranslations } from '../components/content/avatar/avatar.i18n.js';
import { nlddCodeViewerTranslations } from '../components/content/code-viewer/code-viewer.i18n.js';
import { nlddImageTranslations } from '../components/content/image/image.i18n.js';
import { nlddRichTextTranslations } from '../components/content/rich-text/rich-text.i18n.js';
import { nlddTokenTranslations } from '../components/content/token/token.i18n.js';
import { nlddComboBoxTranslations } from '../components/inputs/combo-box/combo-box.i18n.js';
import { nlddDateFieldTranslations } from '../components/inputs/date-field/date-field.i18n.js';
import { nlddDatePickerTranslations } from '../components/inputs/date-picker/date-picker.i18n.js';
import { nlddFileFieldTranslations } from '../components/inputs/file-field/file-field.i18n.js';
import { nlddNumberFieldTranslations } from '../components/inputs/number-field/number-field.i18n.js';
import { nlddSearchFieldTranslations } from '../components/inputs/search-field/search-field.i18n.js';
import { nlddStepperTranslations } from '../components/inputs/stepper/stepper.i18n.js';
import { nlddTextEditorTranslations } from '../components/inputs/text-editor/text-editor.i18n.js';
import { nlddTimeFieldTranslations } from '../components/inputs/time-field/time-field.i18n.js';
import { nlddTimePickerTranslations } from '../components/inputs/time-picker/time-picker.i18n.js';
import { nlddTokenFieldTranslations } from '../components/inputs/token-field/token-field.i18n.js';
import { nlddCardTranslations } from '../components/layout/card/card.i18n.js';
import { nlddCollectionTranslations } from '../components/layout/collection/collection.i18n.js';
import { nlddPageFooterTranslations } from '../components/layout/page-footer/page-footer.i18n.js';
import { nlddSidebarSectionTranslations } from '../components/layout/page-sections/sidebar-section/sidebar-section.i18n.js';
import { nlddPopoverTranslations } from '../components/layout/popover/popover.i18n.js';
import { nlddWindowTranslations } from '../components/layout/window/window.i18n.js';
import { nlddDragHandleCellTranslations } from '../components/lists-and-tables/cells/drag-handle-cell/drag-handle-cell.i18n.js';
import { nlddListItemTranslations } from '../components/lists-and-tables/list-item/list-item.i18n.js';
import { nlddListTranslations } from '../components/lists-and-tables/list/list.i18n.js';
import { nlddTableTranslations } from '../components/lists-and-tables/table/table.i18n.js';
import { nlddBreadcrumbsTranslations } from '../components/navigation/breadcrumbs/breadcrumbs.i18n.js';
import { nlddDocumentTabBarTranslations } from '../components/navigation/document-tab-bar/document-tab-bar.i18n.js';
import { nlddLinkTranslations } from '../components/navigation/link/link.i18n.js';
import { nlddMenuBarTranslations } from '../components/navigation/menu-bar/menu-bar.i18n.js';
import { nlddPaginationTranslations } from '../components/navigation/pagination/pagination.i18n.js';
import { nlddSkipLinkTranslations } from '../components/navigation/skip-link/skip-link.i18n.js';
import { nlddTopNavigationBarTranslations } from '../components/navigation/top-navigation-bar/top-navigation-bar.i18n.js';
import { nlddActivityIndicatorTranslations } from '../components/status-and-feedback/activity-indicator/activity-indicator.i18n.js';
import { nlddBadgeTranslations } from '../components/status-and-feedback/badge/badge.i18n.js';
import { nlddBannerTranslations } from '../components/status-and-feedback/banner/banner.i18n.js';
import { nlddJustInTimeEducationTranslations } from '../components/status-and-feedback/just-in-time-education/just-in-time-education.i18n.js';
import { nlddNotificationTranslations } from '../components/status-and-feedback/notification/notification.i18n.js';
import { nlddProgressBarTranslations } from '../components/status-and-feedback/progress-bar/progress-bar.i18n.js';
import { nlddProgressCircleTranslations } from '../components/status-and-feedback/progress-circle/progress-circle.i18n.js';
import { nlddStepBarTranslations } from '../components/status-and-feedback/step-bar/step-bar.i18n.js';

/** Every text in the package with its Dutch default. */
export const nl = {
	...nlddButtonTranslations,
	...nlddIconButtonTranslations,
	...nlddMenuTranslations,
	...nlddSplitButtonTranslations,
	...nlddToolbarTranslations,
	...nlddAvatarGroupTranslations,
	...nlddAvatarTranslations,
	...nlddCodeViewerTranslations,
	...nlddImageTranslations,
	...nlddRichTextTranslations,
	...nlddTokenTranslations,
	...nlddComboBoxTranslations,
	...nlddDateFieldTranslations,
	...nlddDatePickerTranslations,
	...nlddFileFieldTranslations,
	...nlddNumberFieldTranslations,
	...nlddSearchFieldTranslations,
	...nlddStepperTranslations,
	...nlddTextEditorTranslations,
	...nlddTimeFieldTranslations,
	...nlddTimePickerTranslations,
	...nlddTokenFieldTranslations,
	...nlddCardTranslations,
	...nlddCollectionTranslations,
	...nlddPageFooterTranslations,
	...nlddSidebarSectionTranslations,
	...nlddPopoverTranslations,
	...nlddWindowTranslations,
	...nlddDragHandleCellTranslations,
	...nlddListItemTranslations,
	...nlddListTranslations,
	...nlddTableTranslations,
	...nlddBreadcrumbsTranslations,
	...nlddDocumentTabBarTranslations,
	...nlddLinkTranslations,
	...nlddMenuBarTranslations,
	...nlddPaginationTranslations,
	...nlddSkipLinkTranslations,
	...nlddTopNavigationBarTranslations,
	...nlddActivityIndicatorTranslations,
	...nlddBadgeTranslations,
	...nlddBannerTranslations,
	...nlddJustInTimeEducationTranslations,
	...nlddNotificationTranslations,
	...nlddProgressBarTranslations,
	...nlddProgressCircleTranslations,
	...nlddStepBarTranslations,
};

/** Every translation key a component knows. */
export type TranslationKey = keyof typeof nl;

export default nl;
