/**
 * Nederlandse Digitale Dienst Progress Bar Component (Lit + TypeScript)
 *
 * Exports both NLDDProgressBar and NLDDProgressBarSegmentIndicator.
 *
 * A progress bar that supports a single value (loading-style) or
 * multiple segments (multi-stage progress, or distribution like
 * storage usage). The consumer provides raw values; the component
 * computes percentages from `max`.
 *
 * Two variants:
 * - `progress` (default): segments sum toward `max`; remaining space
 *   is empty track. ARIA reads "X% voltooid".
 * - `distribution`: segments fill the bar; ARIA enumerates segments.
 *
 * If the sum of segment values exceeds `max`, segments are normalized
 * proportionally to fit and a warning is logged.
 *
 * @element nldd-progress-bar
 *
 * @attr {'progress'|'distribution'} variant - Semantics for ARIA and visualization (default: 'progress')
 * @attr {number} max - Total value (default: 100)
 * @attr {number} value - Single-segment shorthand (ignored when segment children are present)
 * @attr {string} color - Color for the single-segment shorthand (default: 'accent')
 * @attr {'sm'|'md'|'lg'} size - Height of the bar (default: 'md')
 * @attr {string} text - Label above the bar (left)
 * @attr {'percentage'|'absolute'|'fraction'} value-format - Format for the displayed value (default: 'percentage')
 * @attr {'inline'|'tooltip'|'none'} value-display - Where the value shows: inline in the caption, in a tooltip on the bar, or hidden (default: 'inline')
 * @attr {string} value-text - Full override of the displayed value
 * @attr {string} accessible-label - Full override of aria-valuetext
 * @attr {boolean} indeterminate - Shows a sliding indicator animation (only without segments)
 * @attr {object} translations - Override translation keys; unset keys fall back to Dutch
 *
 * @slot - Place for nldd-progress-bar-segment-indicator elements
 *
 * @element nldd-progress-bar-segment-indicator
 *
 * @attr {number} value - Share of the parent's total (default 0; <=0 hides segment)
 * @attr {string} color - Color. Semantic (neutral, accent, success, warning, critical) or a Rijkskleur. Default 'accent'.
 * @attr {string} name - Name for screenreader text (optional)
 * @attr {string} tooltip-text - Override of the auto-generated tooltip text
 */
import { LitElement } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { reflectNonDefault } from '../../../utilities/reflect-non-default.js';
import { progressBarStyles, progressBarSegmentIndicatorStyles } from './progress-bar.styles.js';
import { progressBarTemplate, segmentIndicatorTemplate } from './progress-bar.template.js';
import { nlddProgressBarTranslations } from './progress-bar.i18n.js';
import type { NLDDProgressBarTranslations } from './progress-bar.i18n.js';
import '../../content/tooltip/tooltip.js';
import { translate } from '../../../utilities/translations.js';

/** Indeterminate ↔ determinate crossfade duration. Must stay in sync with
 *  --primitives-transition-duration-slow used by the matching CSS animations
 *  and with nldd-progress-circle's matching constant. Exported so the
 *  test suite can cross-check this value against the resolved CSS token. */
export const INDETERMINATE_TRANSITION_MS = 300;

export type ProgressBarVariant = 'progress' | 'distribution';
export type ProgressBarSize = 'sm' | 'md' | 'lg';
export type ProgressBarValueFormat = 'percentage' | 'absolute' | 'fraction';
export type ProgressBarValueDisplay = 'inline' | 'tooltip' | 'none';

export type ProgressBarColor =
	| 'neutral' | 'accent' | 'success' | 'warning' | 'critical'
	| 'lintblauw' | 'donkerblauw' | 'hemelblauw' | 'lichtblauw'
	| 'paars' | 'violet'
	| 'robijnrood' | 'roze' | 'rood' | 'oranje'
	| 'donkergeel' | 'geel'
	| 'donkerbruin' | 'bruin'
	| 'donkergroen' | 'groen' | 'mosgroen' | 'mintgroen';


// # nldd-progress-bar-segment-indicator

@customElement('nldd-progress-bar-segment-indicator')
export class NLDDProgressBarSegmentIndicator extends LitElement {
	static override styles = progressBarSegmentIndicatorStyles;

	@property({ type: Number, reflect: true })
	value = 0;

	@property({ reflect: true, converter: reflectNonDefault<ProgressBarColor>('accent') })
	color: ProgressBarColor = 'accent';

	@property({ type: String, reflect: true })
	name = '';

	/** Tooltip text override. By default, this is generated by the parent based on
	 *  value-format and the segment `name`. Set explicitly for custom text,
	 *  for example with distribution that has units ("200 GB of 500 GB"). */
	@property({ reflect: true, attribute: 'tooltip-text', converter: reflectNonDefault<string>('') })
	tooltipText = '';

	/** Set by the parent based on value-format. Internal state, not a public
	 *  property — consumers use `tooltip-text` to override. */
	@state()
	_autoTooltipText = '';

	get _effectiveTooltip(): string {
		return this.tooltipText || this._autoTooltipText || '';
	}

	override render() {
		return segmentIndicatorTemplate(this);
	}
}


// # nldd-progress-bar

@customElement('nldd-progress-bar')
export class NLDDProgressBar extends LitElement {
	static override styles = progressBarStyles;

	@property({ reflect: true, converter: reflectNonDefault<ProgressBarVariant>('progress') })
	variant: ProgressBarVariant = 'progress';

	@property({ type: Number, reflect: true })
	max = 100;

	@property({ type: Number, reflect: true })
	value: number | null = null;

	@property({ reflect: true, converter: reflectNonDefault<ProgressBarColor>('accent') })
	color: ProgressBarColor = 'accent';

	@property({ reflect: true, converter: reflectNonDefault<ProgressBarSize>('md') })
	size: ProgressBarSize = 'md';

	@property({ reflect: true, converter: reflectNonDefault<string>('') })
	text = '';

	@property({ reflect: true, attribute: 'value-format', converter: reflectNonDefault<ProgressBarValueFormat>('percentage') })
	valueFormat: ProgressBarValueFormat = 'percentage';

	@property({ type: String, reflect: true, attribute: 'value-text' })
	valueText = '';

	@property({ reflect: true, attribute: 'value-display', converter: reflectNonDefault<ProgressBarValueDisplay>('inline') })
	valueDisplay: ProgressBarValueDisplay = 'inline';

	@property({ type: String, reflect: true, attribute: 'accessible-label' })
	accessibleLabel = '';

	@property({ type: Boolean, reflect: true })
	indeterminate = false;

	/** Override one or more translation keys. Unspecified keys fall back to Dutch. */
	@property({ type: Object })
	translations: Partial<NLDDProgressBarTranslations> = {};

	@state()
	private _segmentIndicators: NLDDProgressBarSegmentIndicator[] = [];

	/** True for 300ms after indeterminate=true→false: the indeterminate indicator
	 *  fades out while the segment-indicator grows from 0 to its target value. */
	@state()
	_indeterminateExiting = false;

	/** True for 300ms after indeterminate=false→true: the indeterminate indicator
	 *  fades in while the segment-indicator shrinks from its current width to 0. */
	@state()
	_indeterminateEntering = false;

	private _exitTimeout?: ReturnType<typeof setTimeout>;
	private _enterTimeout?: ReturnType<typeof setTimeout>;

	public _t(key: keyof NLDDProgressBarTranslations): string {
		return translate(this.translations, nlddProgressBarTranslations, key);
	}

	/** Returns true when the user has provided segment children. */
	get _hasSegmentIndicators(): boolean {
		return this._segmentIndicators.length > 0;
	}

	/** Sum of all segment values, or the parent's own value, or 0. */
	get _totalValue(): number {
		if (this._hasSegmentIndicators) {
			return this._segmentIndicators.reduce((sum, s) => sum + Math.max(0, s.value), 0);
		}
		return Math.max(0, this.value ?? 0);
	}

	/** Percentage filled (0–100). */
	get _percentage(): number {
		if (this.max <= 0) return 0;
		return Math.min(100, (this._totalValue / this.max) * 100);
	}

	/** Formatted value string for the caption. */
	get _displayValue(): string {
		if (this.valueText) return this.valueText;
		if (this.indeterminate) return '';
		const total = this._totalValue;
		switch (this.valueFormat) {
			case 'absolute': return `${total}`;
			case 'fraction': return `${total} / ${this.max}`;
			case 'percentage':
			default: return `${Math.round(this._percentage)}%`;
		}
	}

	/** Computed aria-valuetext, unless overridden. */
	get _ariaValueText(): string {
		if (this.accessibleLabel) return this.accessibleLabel;
		if (this.indeterminate) return this._t('components.progress-bar.loading-label');

		const completedSuffix = this._t('components.progress-bar.completed-suffix-text');
		const totalPrefix = this._t('components.progress-bar.total-prefix-text');

		// Single-segment case
		if (!this._hasSegmentIndicators) {
			return `${Math.round(this._percentage)}% ${completedSuffix}`;
		}

		// Multi-segment
		const named = this._segmentIndicators.filter(s => s.name);
		const allNamed = named.length === this._segmentIndicators.length && this._segmentIndicators.length > 0;
		const segmentIndicatorDescriptions = this._segmentIndicators
			.filter(s => s.value > 0)
			.map(s => {
				const pct = this.max > 0 ? Math.round((s.value / this.max) * 100) : 0;
				return s.name ? `${s.name}: ${pct}%` : `${pct}%`;
			});

		if (this.variant === 'distribution') {
			return segmentIndicatorDescriptions.join(', ');
		}

		// Progress variant
		const totalPct = Math.round(this._percentage);
		if (allNamed) {
			return `${segmentIndicatorDescriptions.join(', ')}. ${totalPrefix} ${totalPct}% ${completedSuffix}.`;
		}
		return `${totalPct}% ${completedSuffix}`;
	}

	/** True when the caption is rendered: a label is set, or there's an inline
	 *  value to show (value-display="inline"). */
	get _hasCaption(): boolean {
		return !!this.text || (this.valueDisplay === 'inline' && !!this._displayValue);
	}

	private _attributeObserver?: MutationObserver;

	override firstUpdated(): void {
		this._syncSegmentIndicators();
	}

	override willUpdate(changed: Map<string, unknown>): void {
		// Detect the flip before render so the template keeps both visuals
		// mounted through the crossfade: the indeterminate indicator and the
		// segment-indicator overlap for 300ms so their CSS animations can run
		// (otherwise the outgoing one would unmount and the incoming one mount
		// fresh, and transitions/animations don't run on a freshly mounted
		// element). The `_begin*` methods cancel the opposite phase themselves,
		// so rapid toggles leave no stale state.
		if (changed.has('indeterminate')) {
			const previous = changed.get('indeterminate');
			if (previous === true && !this.indeterminate) {
				this._beginIndeterminateExit();
			} else if (previous === false && this.indeterminate) {
				this._beginIndeterminateEnter();
			}
		}
	}

	override updated(): void {
		// Sync on any update — cheap, and properties like text/valueText also
		// affect tooltip suppression (single-segment + caption).
		this._syncSegmentIndicators();
	}

	/** Indeterminate indicator fades out, segment-indicator grows from 0 to its target — both 300ms
	 *  (matches --primitives-transition-duration-slow and nldd-progress-circle). */
	private _beginIndeterminateExit(): void {
		this._cancelIndeterminateEnter();
		this._indeterminateExiting = true;
		this._exitTimeout = setTimeout(() => {
			this._indeterminateExiting = false;
			this._exitTimeout = undefined;
		}, INDETERMINATE_TRANSITION_MS);
	}

	/** Indeterminate indicator fades in, segment-indicator shrinks from current width to 0 — both 300ms. */
	private _beginIndeterminateEnter(): void {
		this._cancelIndeterminateExit();
		this._indeterminateEntering = true;
		this._enterTimeout = setTimeout(() => {
			this._indeterminateEntering = false;
			this._enterTimeout = undefined;
		}, INDETERMINATE_TRANSITION_MS);
	}

	private _cancelIndeterminateExit(): void {
		if (this._exitTimeout) {
			clearTimeout(this._exitTimeout);
			this._exitTimeout = undefined;
		}
		this._indeterminateExiting = false;
	}

	private _cancelIndeterminateEnter(): void {
		if (this._enterTimeout) {
			clearTimeout(this._enterTimeout);
			this._enterTimeout = undefined;
		}
		this._indeterminateEntering = false;
	}

	/** Computes a segment-indicator's auto-tooltip from the parent's value-format
	 *  and the segment name. Consumers override it per segment with the
	 *  tooltip-text attribute, which wins over this auto-text. */
	private _formatSegmentIndicatorTooltip(seg: NLDDProgressBarSegmentIndicator): string {
		// value-display="none" hides the value, so per-segment tooltips fall
		// back to the segment name only (empty string when unnamed).
		if (this.valueDisplay === 'none') return seg.name ?? '';
		const v = Math.max(0, seg.value);
		const pct = this.max > 0 ? Math.round((v / this.max) * 100) : 0;
		let valuePart: string;
		switch (this.valueFormat) {
			case 'absolute': valuePart = `${v}`; break;
			case 'fraction': valuePart = `${v} / ${this.max}`; break;
			case 'percentage':
			default: valuePart = `${pct}%`; break;
		}
		return seg.name ? `${seg.name}: ${valuePart}` : valuePart;
	}

	override disconnectedCallback(): void {
		super.disconnectedCallback();
		this._cancelIndeterminateExit();
		this._cancelIndeterminateEnter();
		this._attributeObserver?.disconnect();
	}

	private _onSlotChange(): void {
		const slot = this.shadowRoot?.querySelector<HTMLSlotElement>('slot:not([name])');
		const assigned = slot?.assignedElements({ flatten: true }) ?? [];
		// instanceof, not tagName === 'NLDD-PROGRESS-BAR-SEGMENT': tagName
		// comparison breaks under scoped custom-element registries (used in
		// some test environments and cross-frame contexts) where the same
		// class can be registered under a different tag.
		this._segmentIndicators = assigned.filter(
			(el): el is NLDDProgressBarSegmentIndicator => el instanceof NLDDProgressBarSegmentIndicator,
		);

		// Re-observe each segment for value/color/name/tooltip changes so the
		// parent re-computes widths and ARIA when a child attribute mutates.
		// requestUpdate() routes through updated(), which calls _syncSegmentIndicators
		// — no need to call it directly here.
		this._attributeObserver?.disconnect();
		this._attributeObserver = new MutationObserver(() => this.requestUpdate());
		for (const seg of this._segmentIndicators) {
			this._attributeObserver.observe(seg, {
				attributes: true,
				attributeFilter: ['value', 'color', 'name', 'tooltip-text'],
			});
		}

		// Mutating _segmentIndicators above schedules a re-render via Lit's state
		// system, which fires updated() → _syncSegmentIndicators(). Calling it here
		// directly would just run it a second time per slot mutation.
	}

	private _syncSegmentIndicators(): void {
		// Compute per-segment widths. If sum exceeds max, normalize.
		const total = this._totalValue;
		const denominator = total > this.max ? total : this.max;

		if (import.meta.env?.DEV && total > this.max && this._hasSegmentIndicators) {
			console.warn(
				`[nldd-progress-bar] Sum of segment values (${total}) exceeds max (${this.max}). ` +
				'Segments are normalized proportionally.',
			);
		}

		// Unified path for slotted and internal segment-indicators. The internal
		// segment-indicator lives in shadow DOM and is rendered by the template
		// when there are no slotted children — both share the same
		// dynamic-attribute logic here.
		const internalSegmentIndicator = this.shadowRoot?.querySelector<NLDDProgressBarSegmentIndicator>(
			'nldd-progress-bar-segment-indicator',
		) ?? null;
		const allSegmentIndicators: NLDDProgressBarSegmentIndicator[] = internalSegmentIndicator
			? [internalSegmentIndicator, ...this._segmentIndicators]
			: [...this._segmentIndicators];

		// Single visible segment: only surface its auto-tooltip in
		// value-display="tooltip" mode (inline shows the value in the caption,
		// none hides it). Multi-segment always gets per-segment tooltips; an
		// explicit `tooltip-text` attribute still wins.
		const visibleCount = allSegmentIndicators.filter(s => Math.max(0, s.value) > 0).length;
		const suppressAutoTooltip = visibleCount <= 1 && this.valueDisplay !== 'tooltip';

		const isExiting = this._indeterminateExiting;
		const isEntering = this._indeterminateEntering;

		for (const seg of allSegmentIndicators) {
			const v = Math.max(0, seg.value);
			if (v <= 0) {
				seg.hidden = true;
				seg.removeAttribute('data-variant');
				seg._autoTooltipText = '';
				continue;
			}
			seg.hidden = false;
			const pct = denominator > 0 ? (v / denominator) * 100 : 0;
			seg.style.setProperty('--context-progress-bar-segment-indicator-width', `${pct}%`);
			// Progress variant: each segment a capsule. Distribution variant:
			// segments are rectangular, only the track's outer corners are
			// rounded (via overflow:hidden + border-radius on the track).
			seg.setAttribute('data-variant', this.variant);
			seg._autoTooltipText = suppressAutoTooltip ? '' : this._formatSegmentIndicatorTooltip(seg);
			seg.toggleAttribute('data-grow', isExiting);
			seg.toggleAttribute('data-shrink', isEntering);
		}
	}

	private _onSlotChangeBound = this._onSlotChange.bind(this);

	override render() {
		return progressBarTemplate(this, this._onSlotChangeBound);
	}
}

declare global {
	interface HTMLElementTagNameMap {
		'nldd-progress-bar': NLDDProgressBar;
		'nldd-progress-bar-segment-indicator': NLDDProgressBarSegmentIndicator;
	}
}
