/**
 * Generates the package.json "exports" field from src/components/index.ts.
 * Parses export lines to create per-component export paths.
 *
 * WARNING: This script rewrites package.json in-place. After adding or
 * removing a component in index.ts, run `npm run build:exports` and commit
 * the updated package.json.
 *
 * Usage: node scripts/generate-exports.js
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexPath = resolve(__dirname, '../src/components/index.ts');
const packagePath = resolve(__dirname, '../package.json');

const indexContent = readFileSync(indexPath, 'utf-8');
const pkg = JSON.parse(readFileSync(packagePath, 'utf-8'));

// Parse named export lines: export { NLDDButton } from './actions/button/button.ts';
// Note: does not match `export * from` barrel re-exports — only named exports are mapped.
const exportRegex = /export\s+\{[^}]+\}\s+from\s+['"](\.\/[^'"]+)['"]/g;

const componentExports = {};
for (const match of indexContent.matchAll(exportRegex)) {
	const sourcePath = match[1]; // e.g. ./actions/button/button.ts

	// Extract component name from path: ./actions/button/button.js → button
	const parts = sourcePath.split('/');
	const componentName = parts[parts.length - 1].replace(/\.(ts|js)$/, '');

	// Build dist path: ./actions/button/button.js → ./dist/components/actions/button/button.js
	// Assumes tsconfig.build.json rootDir=src, outDir=dist — src/components/… maps to dist/components/….
	const distPath = `./dist/components/${sourcePath.replace(/^\.\//, '').replace(/\.(ts|js)$/, '')}`;

	const exportKey = `./${componentName}`;
	if (componentExports[exportKey]) {
		console.error(`ERROR: Export key collision for "${exportKey}":`);
		console.error(`  Existing: ${componentExports[exportKey].default}`);
		console.error(`  New:      ${distPath}.js`);
		process.exit(1);
	}

	componentExports[exportKey] = {
		types: `${distPath}.d.ts`,
		default: `${distPath}.js`,
	};
}

// Build complete exports map
const exports = {
	'.': './dist/components/components.js',
	// The standalone browser bundle: everything in one minified file, for a page
	// with a plain <script src> and no build step. Anyone bundling themselves uses
	// '.', which externalizes lit and the rest.
	'./bundle': './dist/nldd.min.js',
	...componentExports,
	'./styles': './dist/css/global.css',
	// Same stylesheet without the @font-face rules, for consumers that may not
	// use the Rijksoverheid house fonts (see NOTICES.md). Both family stacks
	// fall through to their system entries on their own.
	'./styles/system-font': './dist/css/global-system-font.css',
	'./styles/variables': './dist/css/variables.css',
	// Deprecated alias of ./styles/variables. Kept pointing at a wrapper that
	// also imports the fonts, because that is what this entry used to ship.
	'./styles/tokens': './dist/css/tokens.css',
	// Opt-in FOUC guard — hides the page until custom elements upgrade. Kept out
	// of ./styles because hiding the body is opinionated; import it explicitly.
	'./styles/fouc': './dist/css/fouc.css',
	// The identity marks, for the tab strip and the home screen. Plain paths, so
	// a bundler resolves them to a URL and a build step can copy them; an entry
	// here is what makes that possible at all, since a package with an exports
	// map answers nothing that is not listed in it.
	'./favicon.svg': './dist/favicon.svg',
	'./touch-icon.png': './dist/touch-icon.png',
	// Breakpoints for consumers that drive matchMedia / layout logic from the
	// same source as CSS. Replaced the ./tokens aggregator, which only ever
	// re-exported this one module.
	'./breakpoints': {
		types: './dist/assets/styles/breakpoints.d.ts',
		default: './dist/assets/styles/breakpoints.js',
	},
	// One layer of texts for the whole package: setTranslations() and the two
	// complete sets, the Dutch defaults as a template and the shipped US English.
	'./translations': {
		types: './dist/utilities/translations.d.ts',
		default: './dist/utilities/translations.js',
	},
	'./translations/nl': {
		types: './dist/translations/nl.generated.d.ts',
		default: './dist/translations/nl.generated.js',
	},
	'./translations/en-US': {
		types: './dist/translations/en-US.d.ts',
		default: './dist/translations/en-US.js',
	},
	// Types only: declares every nldd-* tag for Vue's template type-checking.
	// Generated by scripts/generate-vue-types.js during the build.
	'./vue': {
		types: './dist/types/vue.d.ts',
	},
};

pkg.exports = exports;
writeFileSync(packagePath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');

console.log(`Generated ${Object.keys(componentExports).length} component exports in package.json`);
